import os
from colorama import *
init()
print(Fore.BLUE + Style.BRIGHT + "Pulling :" + Fore.CYAN + Style.DIM)
print()
os.chdir("C:/Users/alexis/Desktop/Blade Website")
os.system("git pull")
print()
print(Fore.BLUE + Style.BRIGHT + "Commiting :" + Fore.CYAN + Style.DIM)
print()
commit = input("Name : ")
os.system('git commit --all -m "{}"'.format(commit))
os.system("git push")
os.system("pause")
input()
##########################################################################################################################################################################
#os.system("")
#os.system("")
#os.system("")
#os.system("")
#os.system("")
#os.system("")
